# Runs the Snyk container scanning workflow on a pull request.
name: Snyk Container (Pull-Request)

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  snyk:
    runs-on: ubuntu-latest
  
    permissions:
      contents: read
      
    strategy:
      matrix:
        project:
          - name: API
            path: src/DemoAPI
            image: demoapi
          - name: Web
            path: src/DemoFrontend
            image: demofrontend
      
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Build the Container image'
        run: |
          echo "Building the container image for ${{ matrix.project.name }}..."
          docker build -t ${{ matrix.project.image }} -f ${{ matrix.project.path }}/Dockerfile ${{ matrix.project.path }} 

      - name: 'Run Snyk to check Docker image for vulnerabilities'
        uses: snyk/actions/docker@master
        env:
          # In order to use the Snyk Action you will need to have a Snyk API token.
          # More details in https://github.com/snyk/actions#getting-your-snyk-token
          # or you can signup for free at https://snyk.io/login
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ matrix.project.image }}
          args: --file=${{ matrix.project.path }}/Dockerfile