# Runs the Snyk container scanning workflow on a pull request.
name: Snyk Container (Pull-Request)

on:
  pull_request:
    branches:
      - main
    paths:
      - src/DemoAPI/Dockerfile

permissions:
  contents: read

jobs:
  snyk:
    runs-on: ubuntu-latest
  
    permissions:
      contents: read
            
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3

      - name: 'Build the Container image'
        run: docker build -t demoapi -f src/DemoAPI/Dockerfile src/DemoAPI

      - name: 'Run Snyk to check Docker image for vulnerabilities'
        uses: snyk/actions/docker@master
        env:
          # In order to use the Snyk Action you will need to have a Snyk API token.
          # More details in https://github.com/snyk/actions#getting-your-snyk-token
          # or you can signup for free at https://snyk.io/login
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: demoapi
          args: --file=src/DemoAPI/Dockerfile