name: secret-scanning-gitleaks

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
  push:

jobs:
  secret-scanning-gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Run Gitleaks'
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }} # Only required for Organizations, not personal accounts.